# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.3.9

options:
  size: 2x
  
pipelines:    
  branches:
    master:
      - step:
          caches:
            - maven
            - terminology
          script:
            - docker login -p $DOCKER_PASSWORD -u $DOCKER_USERNAME
            - mvn -B deploy -P '!docker' -Dsynd.cache.dir=$BITBUCKET_CLONE_DIR/terminology
          i - export DOCKER_COMPOSE_VERSION=1.18.0
            - export DOCKER_COPOSE_URL=https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)
            - curl -L $DOCKER_COPOSE_URL > docker-compose
            - chmod +x docker-compose
            - cd server
            - docker-compose build
            - docker-compose push 
            - ssh root@medserve.online 'docker-compose pull medserve proxy; docker-compose create medserve proxy; docker-compose up -d'
          services:
            - docker

definitions:
  caches:
    terminology: $BITBUCKET_CLONE_DIR/terminology
