version: "2"

services:
  medserve:
    image: dionmcm/medserve
    expose:
      - "8080"
  proxy:
    image: dionmcm/medserve-proxy
    ports:
      - "80:80"
      - "443:443"
    links:
      - medserve
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
