# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
general:
  branches:
    only:
     - master
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Keyscan Github (HACK)
          # added mkdir to work with circleci CLI
          command: mkdir -p ~/.ssh && ssh-keyscan -H medserve.online >> ~/.ssh/known_hosts
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      - run: mkdir -p $HOME/terminology 
      - run: mvn -s settings.xml -B clean deploy -P '!docker' -Dsynd.cache.dir=$HOME/terminology 
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: |
          cd server
          docker-compose build
          docker-compose push
      - run: scp server/docker-compose.yml $DEPLOY_USER@$DEPLOY_HOST:~
        # The line below creates directories referenced in the docker-compose.yml so docker-compose doesn't fall
        # over when using the same compose file to start the services as was used to build them
      - run: ssh $DEPLOY_USER@$DEPLOY_HOST 'mkdir -p ~/fhir-server && mkdir -p ~/medserve-proxy'
      - run: ssh $DEPLOY_USER@$DEPLOY_HOST 'docker-compose --no-build pull medserve proxy && docker-compose --no-build create medserve proxy && docker-compose --no-build up -d'

      - save_cache:
          paths:
            - ~/.m2
            - $HOME/terminology
          key: v1-dependencies-{{ checksum "pom.xml" }}

