# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
general:
  branches:
    only:
     - master
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mkdir -p $HOME/terminology 
      - run: mvn -s settings.xml -B clean deploy -Dsynd.cache.dir=$HOME/terminology 

      - save_cache:
          paths:
            - ~/.m2
            - $HOME/terminology
          key: v1-dependencies-{{ checksum "pom.xml" }}

