version: "2"

services:
  medserve:
    build: fhir-server
    image: dionmcm/medserve
    expose:
      - "8080"
    environment:
      MEDSERVE_FHIR_BASE: ${MEDSERVE_FHIR_BASE}
      SENTRY_DSN: ${MEDSERVE_SENTRY_DSN}
    restart: unless-stopped
  polecat:
    image: johngrimes/polecat
    expose:
      - "80"
    environment:
      POLECAT_FHIR_SERVER: ${MEDSERVE_FHIR_BASE}
      POLECAT_SENTRY_DSN: ${POLECAT_SENTRY_DSN}
    restart: unless-stopped
  proxy:
    build: medserve-proxy
    image: dionmcm/medserve-proxy
    ports:
      - "80:80"
      - "443:443"
    links:
      - medserve
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
