version: "2"

services:
  medserve:
    build: fhir-server
    image: dionmcm/medserve
    expose:
      - "8080"
    environment:
      MEDSERVE_FHIR_BASE: https://medserve.online/fhir
      SENTRY_DSN: ${SENTRY_DSN}
  polecat:
    image: johngrimes/polecat
    expose:
      - "80"
    environment:
      POLECAT_FHIR_SERVER: https://medserve.online/fhir
  proxy:
    build: medserve-proxy
    image: dionmcm/medserve-proxy
    ports:
      - "80:80"
      - "443:443"
    links:
      - medserve
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
